"use client";

import { FormEvent, useState } from "react";

const services = [
  ["✦", "Telehealth Visits", "Connect with a licensed provider from wherever you are, whenever you need care."],
  ["↻", "Prescription Sync", "Keep your medications on track with simple, coordinated prescription support."],
  ["▣", "Lab Results Hub", "See your results in one secure place and understand what they mean for your health."],
  ["♧", "Care Team Direct", "Reach the people who know your care journey with clear, direct communication."],
];
const faqs = [
  ["What is Pulse Health?", "Pulse Health makes it easier to access quality care, manage your health information, and stay connected to your care team in one simple place."],
  ["How do virtual visits work?", "Choose a time, meet your provider securely online, and get a personalized care plan."],
  ["Can I use my insurance?", "We work with many leading insurance plans. Our team can help you understand your options."],
  ["Is my information private?", "Your privacy is central to how we build and operate Pulse Health."],
  ["How quickly can I see a provider?", "Appointments are available based on provider schedules and your care needs."],
];

function UnavailableButton({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  if (className === "sign-in") return <a className={className} href="/login">{children}</a>;
  return <button type="button" className={className} onClick={() => window.alert("This destination is coming soon. Please explore the page for more information.")}>{children}</button>;
}

export default function Home() {
  const [openFaq, setOpenFaq] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [email, setEmail] = useState("");
  const [newsletterMessage, setNewsletterMessage] = useState("");
  const submitNewsletter = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!email || !email.includes("@")) { setNewsletterMessage("Enter a valid email address to subscribe."); return; }
    setNewsletterMessage("Thanks — you’re on the Pulse Health updates list.");
  };
  return <>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <header className="site-header"><div className="container nav-wrap">
      <a className="brand" href="#top" aria-label="Pulse Health home"><span className="brand-mark">✚</span><span>Pulse<span className="brand-accent">Health</span></span></a>
      <button className="menu-toggle" aria-expanded={menuOpen} aria-controls="primary-nav" onClick={() => setMenuOpen(!menuOpen)}><span className="sr-only">Menu</span>☰</button>
      <nav id="primary-nav" className={menuOpen ? "primary-nav open" : "primary-nav"} aria-label="Primary navigation"><a href="#top">Home</a><a href="#services">Services</a><a href="#how-it-works">How It Works</a><a href="#testimonials">Testimonials</a><a href="#contact">Contact</a><UnavailableButton className="sign-in">Sign In</UnavailableButton><a className="button button-pink nav-join" href="#newsletter">Join Pulse <span>→</span></a></nav>
    </div></header>
    <main id="main-content">
      <section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> Trusted by 10,000+ Active Patients</div><h1>Clinical excellence meets <em>everyday accessibility.</em></h1><p className="hero-lede">Your health, simplified. Get expert care, personalized guidance, and the support you need to feel your best—whenever life calls for it.</p><div className="hero-actions"><UnavailableButton className="button button-pink">Book Appointment <span>→</span></UnavailableButton><a className="button button-outline" href="#services">Explore Services <span>↘</span></a></div><div className="rating"><div className="avatar-stack"><span>JM</span><span>AR</span><span>SK</span></div><div><div className="stars" aria-label="Rated 4.9 out of 5">★★★★★</div><strong>4.9/5</strong> <small>from 2,000+ patients</small></div></div></div><div className="hero-art" role="img" aria-label="A caring clinician speaking with a patient during a virtual visit"><div className="art-orb orb-one"/><div className="art-orb orb-two"/><div className="doctor-card"><div className="doctor-photo">Dr<br/><b>+</b></div><div><strong>Care that listens.</strong><small>Personalized for you</small></div><span className="online-dot"/></div><div className="video-card"><div className="video-avatar">PS</div><div><strong>Dr. Priya Shah</strong><small>Available now</small></div><span className="video-icon">▶</span></div><div className="art-caption"><span className="caption-check">✓</span><span><strong>Your care team, connected</strong><small>Every step of the way</small></span></div></div></div></section>
      <section className="trust-bar"><div className="container trust-inner"><span className="trust-label">Featured &amp; Trusted In</span><span>Aetna</span><span className="logo-blue">BlueCross</span><span className="logo-united">UnitedHealthcare</span><span>Cigna</span><span className="logo-humana">Humana</span></div></section>
      <section className="section services" id="services"><div className="container"><div className="section-heading"><div><span className="kicker">WHAT WE OFFER</span><h2>Care that fits your life.</h2></div><p>From everyday questions to ongoing support, we make every part of your health journey feel simpler.</p></div><div className="card-grid service-grid">{services.map(([icon, title, copy]) => <article className="service-card" key={title}><div className="icon-tile">{icon}</div><h3>{title}</h3><p>{copy}</p><a href="#contact">Learn more <span>→</span></a></article>)}</div></div></section>
      <section className="section journey" id="how-it-works"><div className="container"><div className="center-heading"><span className="kicker">SIMPLIFIED JOURNEY</span><h2>Your health, coordinated in three steps.</h2></div><div className="steps"><article><span className="step-number">01</span><div className="step-line"/><h3>Create Your Profile</h3><p>Tell us a little about yourself and your health goals.</p></article><article><span className="step-number">02</span><div className="step-line"/><h3>Book Instant Visit</h3><p>Find the right provider and connect on your schedule.</p></article><article><span className="step-number">03</span><div className="step-line"/><h3>Thrive In Good Health</h3><p>Get ongoing guidance that helps you feel your best.</p></article></div></div></section>
      <section className="section testimonials" id="testimonials"><div className="container"><div className="center-heading"><span className="kicker">REAL STORIES</span><h2>Care that makes a difference.</h2></div><div className="card-grid quote-grid"><article className="quote-card"><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“Pulse Health made getting the care I needed feel easy. I never felt rushed, and my provider truly listened.”</blockquote><div className="reviewer"><span className="review-avatar avatar-a">EM</span><span><strong>Elena Martinez</strong><small>Pulse Health patient</small></span></div></article><article className="quote-card"><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“The whole experience is thoughtful and human. I finally feel like my health is in good hands.”</blockquote><div className="reviewer"><span className="review-avatar avatar-b">DK</span><span><strong>Daniel Kim</strong><small>Pulse Health patient</small></span></div></article></div></div></section>
      <section className="section benefits"><div className="container"><div className="section-heading"><div><span className="kicker">WHY PULSE HEALTH</span><h2>More care. Less complexity.</h2></div><p>Everything you need to feel confident in your care, built around your life.</p></div><div className="card-grid benefit-grid"><article className="benefit-card"><div className="benefit-icon">◷</div><h3>24/7 Access</h3><p>Care and support are there when you need them, day or night.</p><a href="#contact">Learn more <span>→</span></a></article><article className="benefit-card"><div className="benefit-icon">♢</div><h3>HIPAA Compliant</h3><p>Your privacy and security are always our highest priority.</p><a href="#contact">Learn more <span>→</span></a></article><article className="benefit-card"><div className="benefit-icon">▱</div><h3>Insurance Integration</h3><p>Use your benefits with less paperwork and more transparency.</p><a href="#contact">Learn more <span>→</span></a></article></div></div></section>
      <section className="section faq-section"><div className="container faq-grid"><div><span className="kicker">GOOD TO KNOW</span><h2>Questions, answered.</h2><p className="faq-intro">We believe informed patients make empowered decisions. Here are a few things people ask us most.</p><a className="text-link" href="#contact">Still have questions? Talk to us <span>→</span></a></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={openFaq === index ? "faq-item open" : "faq-item"} key={question}><button aria-expanded={openFaq === index} aria-controls={`faq-answer-${index}`} onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span><span className="faq-chevron">⌄</span></button><div id={`faq-answer-${index}`} role="region" className="faq-answer"><p>{answer}</p></div></div>)}</div></div></section>
      <section className="stats"><div className="container stat-grid"><div><strong>10,000<span>+</span></strong><small>Active patients</small></div><div><strong>500<span>+</span></strong><small>Trusted providers</small></div><div><strong>98<span>%</span></strong><small>Patient satisfaction</small></div><div><strong>4.9</strong><small>Average rating</small></div></div></section>
      <section className="newsletter" id="newsletter"><div className="container newsletter-inner"><div><span className="kicker">STAY IN THE KNOW</span><h2>Health insights, delivered.</h2><p>Practical tips and thoughtful updates, straight to your inbox.</p></div><form onSubmit={submitNewsletter}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" aria-describedby="newsletter-status"/><button className="button button-dark" type="submit">Subscribe <span>→</span></button><p id="newsletter-status" className="form-status" aria-live="polite">{newsletterMessage}</p></form></div></section>
    </main>
    <footer className="site-footer" id="contact"><div className="container"><div className="footer-top"><div className="footer-brand"><a className="brand brand-light" href="#top"><span className="brand-mark">✚</span><span>Pulse<span className="brand-accent">Health</span></span></a><p>Care that meets you where you are, and helps you get where you want to go.</p></div><div className="footer-links"><div><h3>Solutions</h3><a href="#services">Telehealth Visits</a><a href="#services">Prescription Sync</a><a href="#services">Lab Results Hub</a><a href="#services">Care Team Direct</a></div><div><h3>Company</h3><a href="#top">About Us</a><a href="#top">Our Providers</a><a href="#top">Careers</a><a href="#contact">Contact</a></div></div></div><div className="footer-bottom"><span>© 2026 Pulse Health System. HIPAA Compliant.</span><span>Designed with care for better health.</span></div></div></footer>
  </>;
}
